mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mybatisplus.entity
  configuration:
    #当selectByMap返回的实体某个字段为空时，返回null，如果不设置这个则实体字段为空时就不返回该字段，这是不符合逻辑的，所以加上
    call-setters-on-nulls: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/campus?useSSL=false&useAffectedRows=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql